# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /client

# add `/client/node_modules/.bin` to $PATH
ENV PATH /client/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package*.json /client/

RUN npm install
RUN npm install @vue/cli@3.7.0 -g

COPY . /client/

EXPOSE 3000

# start app
CMD ["npm", "run", "serve"]
