version: "3.7"
services:
  db:
    build: ./db
    container_name: studies_db
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./db/data:/data/db
  server:
    build: ./server
    container_name: studies_server
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_USER: student
      DATABASE_PASSWORD: password
    depends_on:
      - "db"
    restart: unless-stopped
    volumes:
      - ./server:/server
      - ./server/node_modules
  client:
    build: ./client
    container_name: studies_client
    ports: 
      - "8080:8080"
    depends_on:
      - "server"
    restart: unless-stopped
    volumes:
      - ./client:/client
      - ./client/node_modules