# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /server

# add `/server/node_modules/.bin` to $PATH
#ENV PATH /server/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package*.json ./

RUN npm install

COPY . .


# start server
CMD node_modules/nodemon/bin/nodemon.js index.js
