# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /server

# add `/server/node_modules/.bin` to $PATH
ENV PATH /server/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json package.json
RUN npm install

COPY . /server/

# start server
CMD ["npm", "run", "start"]
